# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: OldUnreal.UnrealTournamentGOTY
PackageVersion: '469'
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: nullsoft
NestedInstallerFiles:
- RelativeFilePath: UT_GOTY.exe
UpgradeBehavior: install
Protocols:
- unreal
FileExtensions:
- umod
ProductCode: OldUnreal_ut99
ReleaseDate: 2025-04-21
AppsAndFeaturesEntries:
- DisplayName: Unreal Tournament GOTY
  Publisher: Epic Games
  DisplayVersion: OldUnreal Edition
  ProductCode: OldUnreal_ut99
InstallationMetadata:
  DefaultInstallLocation: C:\UnrealTournament
Installers:
- Architecture: x86
  InstallerUrl: https://www.oldunreal.com/site/assets/files/1107/ut_goty.zip
  InstallerSha256: A74EFB74C0224899B6DE157D0C867E4B38618415D806E3FBF4CF2D1CD4F7B248
ManifestType: installer
ManifestVersion: 1.9.0
